#...............................................................................
#
#  This file is part of the Jancy toolkit.
#
#  Jancy is distributed under the MIT license.
#  For details see accompanying license.txt file,
#  the public copy of which is also available at:
#  http://tibbo.com/downloads/archive/jancy/license.txt
#
#...............................................................................

dist:     trusty
sudo:     required
language: cpp

os:
    - linux
    - osx

compiler:
    - gcc
    - clang

env:
    - TARGET_CPU=x86 BUILD_CONFIGURATION=Debug
    - TARGET_CPU=x86 BUILD_CONFIGURATION=Release
    - TARGET_CPU=amd64 BUILD_CONFIGURATION=Debug
    - TARGET_CPU=amd64 BUILD_CONFIGURATION=Release

matrix:
    exclude:
        - os: osx
          env: TARGET_CPU=x86 BUILD_CONFIGURATION=Debug
        - os: osx
          env: TARGET_CPU=x86 BUILD_CONFIGURATION=Release

before_install:
    - source travis/install-$TRAVIS_OS_NAME.sh

    - LLVM_VERSION=3.4.2
    - LLVM_TAR=llvm-$LLVM_VERSION.src.tar.gz
    - LLVM_URL=http://releases.llvm.org/$LLVM_VERSION/$LLVM_TAR

    - wget --quiet $LLVM_URL
    - mkdir -p llvm
    - tar --strip-components=1 -xzf $LLVM_TAR -C llvm

script:
    - THIS_DIR=`pwd`

    - mkdir llvm/build
    - cd llvm/build
    - cmake .. $LLVM_BUILD_32_BITS -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DHAVE_SANITIZER_MSAN_INTERFACE_H=0 -DLLVM_TARGETS_TO_BUILD=X86 -DLLVM_ENABLE_TERMINFO=OFF -DLLVM_INCLUDE_DOCS=OFF -DLLVM_INCLUDE_EXAMPLES=OFF -DLLVM_INCLUDE_TESTS=OFF -DLLVM_INCLUDE_TOOLS=OFF
    - make

    - cd $THIS_DIR
    - echo "set (LLVM_INC_DIR $THIS_DIR/llvm/include $THIS_DIR/llvm/build/include)" >> paths.cmake
    - echo "set (LLVM_LIB_DIR $THIS_DIR/llvm/build/lib)" >> paths.cmake
    - echo "set (LLVM_CMAKE_DIR $THIS_DIR/llvm/build/share/llvm/cmake)" >> paths.cmake

    - mkdir build
    - cd build
    - cmake .. -DAXL_CPU=$TARGET_CPU -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION
    - make
    - make test
