#...............................................................................
#
#  This file is part of the Jancy toolkit.
#
#  Jancy is distributed under the MIT license.
#  For details see accompanying license.txt file,
#  the public copy of which is also available at:
#  http://tibbo.com/downloads/archive/jancy/license.txt
#
#...............................................................................

dist:     trusty
sudo:     required
language: cpp

os:
    - linux
    - osx

compiler:
    - gcc
    - clang

env:
    - LLVM_VERSION=3.4.2 TARGET_CPU=x86 BUILD_CONFIGURATION=Debug
    - LLVM_VERSION=3.4.2 TARGET_CPU=x86 BUILD_CONFIGURATION=Release
    - LLVM_VERSION=3.4.2 TARGET_CPU=amd64 BUILD_CONFIGURATION=Debug
    - LLVM_VERSION=3.4.2 TARGET_CPU=amd64 BUILD_CONFIGURATION=Release
    - LLVM_VERSION=3.9.1 CPP_STD=c++11 TARGET_CPU=x86 BUILD_CONFIGURATION=Debug
    - LLVM_VERSION=3.9.1 CPP_STD=c++11 TARGET_CPU=x86 BUILD_CONFIGURATION=Release
    - LLVM_VERSION=3.9.1 CPP_STD=c++11 TARGET_CPU=amd64 BUILD_CONFIGURATION=Debug
    - LLVM_VERSION=3.9.1 CPP_STD=c++11 TARGET_CPU=amd64 BUILD_CONFIGURATION=Release

matrix:
    exclude:
        - os:       osx
          compiler: gcc

        - os:  osx
          env: LLVM_VERSION=3.4.2 TARGET_CPU=x86 BUILD_CONFIGURATION=Debug

        - os:  osx
          env: LLVM_VERSION=3.4.2 TARGET_CPU=x86 BUILD_CONFIGURATION=Release

        - os:  osx
          env: LLVM_VERSION=3.9.1 CPP_STD=c++11 TARGET_CPU=x86 BUILD_CONFIGURATION=Debug

        - os:  osx
          env: LLVM_VERSION=3.9.1 CPP_STD=c++11 TARGET_CPU=x86 BUILD_CONFIGURATION=Release

install:
    - source jancy/ci/travis/set-env.sh
    - bash jancy/ci/travis/install-$TRAVIS_OS_NAME.sh
    - bash -e jancy/ci/travis/download-llvm.sh

script:
    - echo "if (NOT \"$CPP_STD\" STREQUAL \"\")" >> settings.cmake
    - echo "    axl_override_setting (GCC_FLAG_CPP_STANDARD -std=$CPP_STD)" >> settings.cmake
    - echo "endif ()" >> settings.cmake

    - mkdir build
    - cd build
    - cmake .. -DTARGET_CPU=$TARGET_CPU -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION
    - make
    - ctest --output-on-failure
