#...............................................................................
#
#  This file is part of the Jancy toolkit.
#
#  Jancy is distributed under the MIT license.
#  For details see accompanying license.txt file,
#  the public copy of which is also available at:
#  http://tibbo.com/downloads/archive/jancy/license.txt
#
#...............................................................................

dist:     trusty
sudo:     required
language: cpp

compiler:
    - gcc
    - clang

before_install:
    - LUA_VERSION=5.2

    - LLVM_VERSION=3.4.2
    - LLVM_TAR=llvm-$LLVM_VERSION.src.tar.gz
    - LLVM_URL=http://releases.llvm.org/$LLVM_VERSION/$LLVM_TAR

    - CMAKE_VERSION=3.3.2
    - CMAKE_VERSION_DIR=v3.3
    - CMAKE_OS=Linux-x86_64
    - CMAKE_TAR=cmake-$CMAKE_VERSION-$CMAKE_OS.tar.gz
    - CMAKE_URL=http://www.cmake.org/files/$CMAKE_VERSION_DIR/$CMAKE_TAR
    - CMAKE_DIR=$(pwd)/cmake-$CMAKE_VERSION

    - wget --quiet $CMAKE_URL
    - mkdir -p $CMAKE_DIR
    - tar --strip-components=1 -xzf $CMAKE_TAR -C $CMAKE_DIR
    - export PATH=$CMAKE_DIR/bin:$PATH

    - wget --quiet $LLVM_URL
    - mkdir -p llvm
    - tar --strip-components=1 -xzf $LLVM_TAR -C llvm

    - sudo apt-get -qq update
    - sudo apt-get install -y liblua${LUA_VERSION}-dev
    - sudo apt-get install -y p7zip-full

script:
    - THIS_DIR=`pwd`

    - mkdir llvm/build
    - cd llvm/build
    - cmake .. -DLLVM_TARGETS_TO_BUILD=X86 -DLLVM_ENABLE_TERMINFO=OFF -DLLVM_INCLUDE_DOCS=OFF -DLLVM_INCLUDE_EXAMPLES=OFF -DLLVM_INCLUDE_TESTS=OFF -DLLVM_INCLUDE_TOOLS=OFF
    - make

    - cd $THIS_DIR
    - echo "set (LLVM_INC_DIR $THIS_DIR/llvm/include $THIS_DIR/llvm/build/include)" >> paths.cmake
    - echo "set (LLVM_LIB_DIR $THIS_DIR/llvm/build/lib)" >> paths.cmake
    - echo "set (LLVM_CMAKE_DIR $THIS_DIR/llvm/build/share/llvm/cmake)" >> paths.cmake

    - mkdir build
    - cd build
    - cmake ..
    - make
    - make test
